repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
    -   id: check-json
    -   id: requirements-txt-fixer
-   repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
    -   id: black
        args: [--line-length=100,]
-   repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
    -   id: isort
        args: [--line-length=100]
-   repo: https://github.com/PyCQA/bandit
    rev: 1.7.5
    hooks:
    -   id: bandit
        exclude: ^tests/
        args:
        - -s
        - B404,B603
-   repo: https://github.com/motet-a/jinjalint
    rev: '0.5'
    hooks:
    -   id: jinjalint
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.3.0
    hooks:
    -   id: mypy
        additional_dependencies: [types-pytz==2023.3.0.0]
        args: [--follow-imports=silent,
               --ignore-missing-imports,
               --show-column-numbers,
               --no-pretty,
               ]
-   repo: https://github.com/thibaudcolas/curlylint
    rev: v0.13.1
    hooks:
    -   id: curlylint
-   repo: https://github.com/klieret/jekyll-relative-url-check
    rev: v2.0.1
    hooks:
    -   id: jekyll-relative-url-check-html
    -   id: jekyll-relative-url-check-markdown
